package com.review.pojo;

import java.util.Date;

public class ReviewScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.SCORE_ID
     *
     * @mbggenerated
     */
    private String scoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.SCORE_USER_ID
     *
     * @mbggenerated
     */
    private String scoreUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.SCORE_USER_NAME
     *
     * @mbggenerated
     */
    private String scoreUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.SCORE_USER_DESC
     *
     * @mbggenerated
     */
    private String scoreUserDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.SCORE_VALUE
     *
     * @mbggenerated
     */
    private String scoreValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.SCORE_TIME
     *
     * @mbggenerated
     */
    private Date scoreTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.REVIEWPRJ_ID
     *
     * @mbggenerated
     */
    private String reviewprjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEW_SCORE.REVIEW_NAME
     *
     * @mbggenerated
     */
    private String reviewName;



    public ReviewScore(){}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.SCORE_ID
     *
     * @return the value of REVIEW_SCORE.SCORE_ID
     *
     * @mbggenerated
     */
    public String getScoreId() {
        return scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.SCORE_ID
     *
     * @param scoreId the value for REVIEW_SCORE.SCORE_ID
     *
     * @mbggenerated
     */
    public void setScoreId(String scoreId) {
        this.scoreId = scoreId == null ? null : scoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.SCORE_USER_ID
     *
     * @return the value of REVIEW_SCORE.SCORE_USER_ID
     *
     * @mbggenerated
     */
    public String getScoreUserId() {
        return scoreUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.SCORE_USER_ID
     *
     * @param scoreUserId the value for REVIEW_SCORE.SCORE_USER_ID
     *
     * @mbggenerated
     */
    public void setScoreUserId(String scoreUserId) {
        this.scoreUserId = scoreUserId == null ? null : scoreUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.SCORE_USER_NAME
     *
     * @return the value of REVIEW_SCORE.SCORE_USER_NAME
     *
     * @mbggenerated
     */
    public String getScoreUserName() {
        return scoreUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.SCORE_USER_NAME
     *
     * @param scoreUserName the value for REVIEW_SCORE.SCORE_USER_NAME
     *
     * @mbggenerated
     */
    public void setScoreUserName(String scoreUserName) {
        this.scoreUserName = scoreUserName == null ? null : scoreUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.SCORE_USER_DESC
     *
     * @return the value of REVIEW_SCORE.SCORE_USER_DESC
     *
     * @mbggenerated
     */
    public String getScoreUserDesc() {
        return scoreUserDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.SCORE_USER_DESC
     *
     * @param scoreUserDesc the value for REVIEW_SCORE.SCORE_USER_DESC
     *
     * @mbggenerated
     */
    public void setScoreUserDesc(String scoreUserDesc) {
        this.scoreUserDesc = scoreUserDesc == null ? null : scoreUserDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.SCORE_VALUE
     *
     * @return the value of REVIEW_SCORE.SCORE_VALUE
     *
     * @mbggenerated
     */
    public String getScoreValue() {
        return scoreValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.SCORE_VALUE
     *
     * @param scoreValue the value for REVIEW_SCORE.SCORE_VALUE
     *
     * @mbggenerated
     */
    public void setScoreValue(String scoreValue) {
        this.scoreValue = scoreValue == null ? null : scoreValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.SCORE_TIME
     *
     * @return the value of REVIEW_SCORE.SCORE_TIME
     *
     * @mbggenerated
     */
    public Date getScoreTime() {
        return scoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.SCORE_TIME
     *
     * @param scoreTime the value for REVIEW_SCORE.SCORE_TIME
     *
     * @mbggenerated
     */
    public void setScoreTime(Date scoreTime) {
        this.scoreTime = scoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.REVIEWPRJ_ID
     *
     * @return the value of REVIEW_SCORE.REVIEWPRJ_ID
     *
     * @mbggenerated
     */
    public String getReviewprjId() {
        return reviewprjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.REVIEWPRJ_ID
     *
     * @param reviewprjId the value for REVIEW_SCORE.REVIEWPRJ_ID
     *
     * @mbggenerated
     */
    public void setReviewprjId(String reviewprjId) {
        this.reviewprjId = reviewprjId == null ? null : reviewprjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEW_SCORE.REVIEW_NAME
     *
     * @return the value of REVIEW_SCORE.REVIEW_NAME
     *
     * @mbggenerated
     */
    public String getReviewName() {
        return reviewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEW_SCORE.REVIEW_NAME
     *
     * @param reviewName the value for REVIEW_SCORE.REVIEW_NAME
     *
     * @mbggenerated
     */
    public void setReviewName(String reviewName) {
        this.reviewName = reviewName == null ? null : reviewName.trim();
    }
}